/**
 * Utilitário para gerar arquivos padrão de SEO e cache.
 */

export function generateRobotsTxt() {
  return "User-agent: *\nAllow: /\nSitemap: /sitemap.xml\n";
}

export function generateSitemapXml(baseUrl, pages) {
  const base = (baseUrl || 'https://example.com').replace(/\/$/, '');
  const urls = pages.map(p => {
    const loc = p === 'index' ? base : `${base}/${p}/`;
    return `  <url>\n    <loc>${loc}</loc>\n  </url>`;
  }).join('\n');
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
}

export function generateLlmsTxt(siteName, siteDesc, baseUrl, pages = []) {
  const name = siteName || 'Website';
  const desc = siteDesc || 'Generated by Renderit.builder';
  const base = (baseUrl || 'https://example.com').replace(/\/$/, '');
  
  const pageList = pages.map(p => {
    const url = p === 'index' ? base : `${base}/${p}/`;
    return `- [${p}](${url})`;
  }).join('\n');

  return `# ${name}\n\n${desc}\n\n## Pages\n\n${pageList}\n\n> Documentação amigável para LLMs provida por padrão no modo estático.`;
}

export function generateHtaccess() {
  return `<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresDefault "access plus 1 month"
  ExpiresByType text/html "access plus 0 seconds"
  ExpiresByType text/xml "access plus 0 seconds"
  ExpiresByType application/xml "access plus 0 seconds"
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript
</IfModule>`;
}
